### PR TITLE
feat(events): add ip address to raw login events

### PR DESCRIPTION
**Pull request by bjagg**
##### Checklist

-   [X] the [individual contributor license agreement][] is signed
-   [X] commit message follows [commit guidelines][]
-   [ ] tests are included
-   [ ] documentation is changed or added

##### Description of change

An implementer is consuming raw events for analytics. They wish to capture user IP addresses for geolocation. This change adds user IP addresses to Login events.

Tests are not included given the triviality of the change (and some manual testing to confirm correct operation).

There is no documentation around event details.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Review by ChristianMurphy — COMMENTED** [review]
Could we put this behind a flag?
This is probably fine for some US schools.
But, could be considered protected PII for folks in the EU (under GDPR), California (under CCPA), Canada (under DCIA), etc.

---

Not in scope of this PR.
But there be some benefit to having a broader discussion on privacy and to review data uPortal is handling, to ensure everything conforms with the latest privacy standards.

**Comment by bjagg** [comment]
Thanks @ChristianMurphy !

**Review by cbeach47 — APPROVED** [review]
Apart from @ChristianMurphy 's comment on putting this behind a flag, looks good.

**Comment by jgribonvald** [comment]
I'm totaly agree with Christian comment. IP address is a personal data that shouldn't be used in analytics. This is only stocked in access logs for security concerns and not accessed by anybody.

**Review by ChristianMurphy — APPROVED** [review]

**Pull request merged**
