### PR TITLE
feat/AnalyticsEventUpdate add new features to AnalyticsPortalEvent an…

### PR DESCRIPTION
**Pull request by mgillian**
…d factory

##### Checklist

-   [x ] the [individual contributor license agreement][] is signed
-   [x ] commit message follows [commit guidelines][]

##### Description of change

Additional data is captured as part of an AnalyticsPortalEvent being generated by the UI call to the AnalyticsPortalEventControlller REST endpoint

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Review by ChristianMurphy — CHANGES_REQUESTED** [review]
Thanks @mgillian!
When you get a chance, please run `./gradlew goJF` to format the code so CI passes, thanks!

**Review by ChristianMurphy — COMMENTED** [review]
Code formatting looks good

**Review by ChristianMurphy — APPROVED** [review]
Formatting looks good, I have not tested otherwised

**Review by cbeach47 — APPROVED** [review]
Confirmed locally. LGTM 👍

**Pull request merged**
