### PR TITLE
fix: correct some Less entries

### PR DESCRIPTION
**Pull request by bjagg**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

A deployer reported build failing due to some Less lint issues. This PR represents the corrections to pass the tests.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]

**Comment by ChristianMurphy** [comment]
Less file looks good, thanks @bjagg!

In an unrelated turn of events, the jquery webjar seems to have gone missing from maven central?
https://github.com/uPortal-Project/uPortal/actions/runs/3761870066/jobs/6394795730#step:4:32

**Comment by bjagg** [comment]
That is a very very old version. Maybe it's time to remove it?

**Comment by ChristianMurphy** [comment]
Restarted CI again this morning to see if it was a temporary resolution issue. ♻️ 

Also started a redeploy of `jstree` on webjars to see if that will help 🏗️ 

> That is a very very old version. Maybe it's time to remove it?

ideally yes.
Though this is a transitive dependency, through `jstree`, we'd need to wait for an upgrade there (which may be a bit, the author is recovering from an injury), or replace `jstree` with another library.

**Review by jgribonvald — APPROVED** [review]

**Comment by jgribonvald** [comment]
> Restarted CI again this morning to see if it was a temporary resolution issue. ♻️
> 
> Also started a redeploy of `jstree` on webjars to see if that will help 🏗️
> 
> > That is a very very old version. Maybe it's time to remove it?
> 
> ideally yes. Though this is a transitive dependency, through `jstree`, we'd need to wait for an upgrade there (which may be a bit, the author is recovering from an injury [according to the project readme](https://github.com/vakata/jstree#i-had-a-bad-cycling-crash-in-august-and-i-am-still-recovering-after-the-surgery-i-have-a-second-surgery-planned-for-october-and-should-be-back-working-on-jstree-in-the-second-half-of-october-i-am-sorry-for-the-delays-and-trouble-this-may-cause)), or replace `jstree` with another library.

In my context I'm using custom web-components in place, because in several case we need only small component or a component with few features so which is really small. For complexe case we can find and use library for that.

**Comment by bjagg** [comment]
Yay -- it passed!

**Pull request merged**
