### PR TITLE
Increasing Test Coverage

### PR DESCRIPTION
**Pull request by HimanshiVerma05**
##### Checklist
-   [X] the [individual contributor license agreement][] is signed
-   [X] commit message follows [commit guidelines][]
-   [X] tests are included

##### Description of change
Increased the code test coverage by adding new test cases .

### CODE REVIEW

**Review by ChristianMurphy — COMMENTED** [review]
Welcome @HimanshiVerma05!
Thanks for sharing new test cases!

When you have a chance could you apply the Google Java format to the code.
You could do this manually, or automatically with `./gradlew goJF`.

**Comment by HimanshiVerma05** [comment]
> Welcome @HimanshiVerma05! Thanks for sharing new test cases!
> 
> When you have a chance could you apply the Google Java format to the code. You could do this manually, or automatically with `./gradlew goJF`.

Hi @ChristianMurphy  . I have applied google java format in the application and verified it also . But I can do it again

**Comment by HimanshiVerma05** [comment]
Hi @ChristianMurphy . Done !

**Review by ChristianMurphy — APPROVED** [review]
Thanks @HimanshiVerma05! 🙇

**Pull request merged**
