### PR TITLE
Added CachingPersonAttributeDaoImpl bean and myunivCachingPersonDbJdbcAttributeSource bean to the User Attributes docs

### PR DESCRIPTION
**Pull request by 555vedant**
This pull request adds configuration for the CachingPersonAttributeDaoImpl bean and myunivCachingPersonDbJdbcAttributeSource bean to the User Attributes documentation in README.md. The new bean merges user attribute sources, enhancing the flexibility and performance of user data retrieval in uPortal.

-> Changes Made

   1)Added a CachingPersonAttributeDaoImpl bean  and myunivCachingPersonDbJdbcAttributeSource bean        definition to improve attribute merging.

  2)Updated the documentation to guide users on configuring multiple user attribute sources effectively.

### CODE REVIEW

**Comment by 555vedant** [comment]
is it okay ??

**Comment by 555vedant** [comment]
@ChristianMurphy is it okay to merge ?

**Comment by ChristianMurphy** [comment]
@555vedant enhance your calm, give people a chance to review. 🙂

**Comment by 555vedant** [comment]
@jonathanmtran  sir why you are not merging this pull ??

**Comment by jonathanmtran** [comment]
As ChristianMurphy mentioned, one needs to have some patience when it comes to pull request reviews.

Thanks for migrating the documentation from Confluence

**Review by jonathanmtran — APPROVED** [review]

**Pull request merged**
