### PR TITLE
feature/UPSE-286 update to support Java 11

### PR DESCRIPTION
**Pull request by mgillian**
##### Checklist

-   [X ] the [individual contributor license agreement][] is signed
-   [X ] commit message follows [commit guidelines][]

##### Description of change

Provide support for build/install against Java 11, as well as Java 8

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Nice, thanks @mgillian!
Could we add Java 11 to the CI test matrix, here:
https://github.com/uPortal-Project/uPortal/blob/cb1d5335b9209d6214777fefdce9c641ba083e14/.github/workflows/CI.yml#L22-L23
Adding
```yaml
- 11
```
to the list?

**Comment by mgillian** [comment]
done.

Michael

**Comment by ChristianMurphy** [comment]
It looks like the Zulu flavor of Java on Windows is working, but is timing out before it could finish.
We can probably adjust this line https://github.com/uPortal-Project/uPortal/blob/cb1d5335b9209d6214777fefdce9c641ba083e14/.github/workflows/CI.yml#L25
To give a bit more wiggle room for builds that take longer.
30 min, 45 min, or even 60 min would probably be fine.

**Comment by jgribonvald** [comment]
Did you watch if this fix the issue: https://github.com/uPortal-Project/uPortal-start/issues/570 ?

**Review by jgribonvald — COMMENTED** [review]
I've tested the build locally to see what happen, and it's building.
After there is a lot of warning with error prone on code...

@mgillian are you deploying this uPortal build ?

**Review by bjagg — APPROVED** [review]
🥇

**Pull request merged**
